### ISSUE TITLE
Camera feed frozen when app is opened by clicking the widget

### ISSUE THREAD

**Issue by hessijames79** [gdombiak/OctoPod#494] opened 2021-06-08 19:37 UTC
When opening the app via the widget (in contrast to the app icon), the camera feed is frozen. Swiping left then right thus switching the camera twice unfreezes the video.

Patrick

**Comment by gdombiak** [comment] 2021-07-21 06:10
This seems to be a duplicate of #474 which I just fixed for the next release. Thanks for reporting this issue.

Regards,
Gaston

**Closed by gdombiak** 2021-07-21 06:10 UTC
